/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package modeloinventario;

import javax.swing.JOptionPane;

/**
 *
 * @author Vicente
 */
public class ingreso extends javax.swing.JFrame {

    /**
     * Creates new form ingreso
     */
    public ingreso() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        demanda1Txt = new javax.swing.JTextField();
        demanda5Txt = new javax.swing.JTextField();
        demanda2Txt = new javax.swing.JTextField();
        demanda3Txt = new javax.swing.JTextField();
        demanda4Txt = new javax.swing.JTextField();
        demandaFr5Txt = new javax.swing.JTextField();
        demandaFr1Txt = new javax.swing.JTextField();
        demandaFr2Txt = new javax.swing.JTextField();
        demandaFr3Txt = new javax.swing.JTextField();
        demandaFr4Txt = new javax.swing.JTextField();
        demandaFa5Txt = new javax.swing.JTextField();
        demandaFa4Txt = new javax.swing.JTextField();
        demandaFa3Txt = new javax.swing.JTextField();
        demandaFa2Txt = new javax.swing.JTextField();
        demandaFa1Txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        retraso1Txt = new javax.swing.JTextField();
        retraso5Txt = new javax.swing.JTextField();
        retraso2Txt = new javax.swing.JTextField();
        retraso3Txt = new javax.swing.JTextField();
        retraso4Txt = new javax.swing.JTextField();
        retrasoFr5Txt = new javax.swing.JTextField();
        retrasoFr1Txt = new javax.swing.JTextField();
        retrasoFr2Txt = new javax.swing.JTextField();
        retrasoFr3Txt = new javax.swing.JTextField();
        retrasoFr4Txt = new javax.swing.JTextField();
        retrasoFa5Txt = new javax.swing.JTextField();
        retrasoFa4Txt = new javax.swing.JTextField();
        retrasoFa3Txt = new javax.swing.JTextField();
        retrasoFa2Txt = new javax.swing.JTextField();
        retrasoFa1Txt = new javax.swing.JTextField();
        cantidadPedidoTxt = new javax.swing.JTextField();
        inventarioInicialTxt = new javax.swing.JTextField();
        puntoReordenTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aleRetraso1 = new javax.swing.JTextField();
        aleRetraso2 = new javax.swing.JTextField();
        aleRetraso3 = new javax.swing.JTextField();
        aleRetraso4 = new javax.swing.JTextField();
        aleRetraso5 = new javax.swing.JTextField();
        aleRetraso6 = new javax.swing.JTextField();
        aleRetraso7 = new javax.swing.JTextField();
        aleRetraso8 = new javax.swing.JTextField();
        aleRetraso9 = new javax.swing.JTextField();
        aleRetraso10 = new javax.swing.JTextField();
        aleRetraso11 = new javax.swing.JTextField();
        aleRetraso12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aleDemanda1 = new javax.swing.JTextField();
        aleDemanda2 = new javax.swing.JTextField();
        aleDemanda3 = new javax.swing.JTextField();
        aleDemanda4 = new javax.swing.JTextField();
        aleDemanda5 = new javax.swing.JTextField();
        aleDemanda6 = new javax.swing.JTextField();
        aleDemanda7 = new javax.swing.JTextField();
        aleDemanda8 = new javax.swing.JTextField();
        aleDemanda9 = new javax.swing.JTextField();
        aleDemanda10 = new javax.swing.JTextField();
        aleDemanda11 = new javax.swing.JTextField();
        aleDemanda12 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Demanda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        demanda1Txt.setToolTipText("");
        demanda1Txt.setName("demanda1txt"); // NOI18N
        demanda1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demanda1TxtActionPerformed(evt);
            }
        });
        getContentPane().add(demanda1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, -1));
        getContentPane().add(demanda5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 40, -1));
        getContentPane().add(demanda2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));
        getContentPane().add(demanda3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 40, -1));
        getContentPane().add(demanda4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, -1));

        demandaFr5Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demandaFr5TxtActionPerformed(evt);
            }
        });
        getContentPane().add(demandaFr5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 60, -1));
        getContentPane().add(demandaFr1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, -1));
        getContentPane().add(demandaFr2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 60, -1));

        demandaFr3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demandaFr3TxtActionPerformed(evt);
            }
        });
        getContentPane().add(demandaFr3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, -1));
        getContentPane().add(demandaFr4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 60, -1));

        demandaFa5Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demandaFa5TxtActionPerformed(evt);
            }
        });
        getContentPane().add(demandaFa5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 60, -1));

        demandaFa4Txt.setToolTipText("");
        getContentPane().add(demandaFa4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 60, -1));

        demandaFa3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demandaFa3TxtActionPerformed(evt);
            }
        });
        getContentPane().add(demandaFa3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, -1));
        getContentPane().add(demandaFa2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 60, -1));
        getContentPane().add(demandaFa1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, -1));

        jLabel2.setText("Retraso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        retraso1Txt.setName("demanda1txt"); // NOI18N
        retraso1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retraso1TxtActionPerformed(evt);
            }
        });
        getContentPane().add(retraso1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 40, -1));
        getContentPane().add(retraso5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 40, -1));
        getContentPane().add(retraso2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 40, -1));
        getContentPane().add(retraso3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 40, -1));
        getContentPane().add(retraso4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 40, -1));

        retrasoFr5Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrasoFr5TxtActionPerformed(evt);
            }
        });
        getContentPane().add(retrasoFr5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 60, -1));
        getContentPane().add(retrasoFr1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, -1));
        getContentPane().add(retrasoFr2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 60, -1));

        retrasoFr3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrasoFr3TxtActionPerformed(evt);
            }
        });
        getContentPane().add(retrasoFr3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 60, -1));
        getContentPane().add(retrasoFr4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 60, -1));

        retrasoFa5Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrasoFa5TxtActionPerformed(evt);
            }
        });
        getContentPane().add(retrasoFa5Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, -1));
        getContentPane().add(retrasoFa4Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 60, -1));

        retrasoFa3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrasoFa3TxtActionPerformed(evt);
            }
        });
        getContentPane().add(retrasoFa3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 60, -1));
        getContentPane().add(retrasoFa2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 60, -1));

        retrasoFa1Txt.setToolTipText("");
        getContentPane().add(retrasoFa1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, -1));
        getContentPane().add(cantidadPedidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 100, 30));
        getContentPane().add(inventarioInicialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 100, 30));

        puntoReordenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoReordenTxtActionPerformed(evt);
            }
        });
        getContentPane().add(puntoReordenTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 100, 30));

        jLabel3.setText("Q");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        jLabel4.setText("I0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jLabel5.setText("R");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        aleRetraso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso1ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 40, 30));

        aleRetraso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso2ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 40, 30));

        aleRetraso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso3ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 40, 30));

        aleRetraso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso4ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 40, 30));

        aleRetraso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso5ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 40, 30));

        aleRetraso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso6ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 40, 30));

        aleRetraso7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso7ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 40, 30));

        aleRetraso8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso8ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 40, 30));

        aleRetraso9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso9ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 40, 30));

        aleRetraso10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso10ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 40, 30));

        aleRetraso11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso11ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 40, 30));

        aleRetraso12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleRetraso12ActionPerformed(evt);
            }
        });
        getContentPane().add(aleRetraso12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 40, 30));

        jLabel6.setText("D");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        aleDemanda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda1ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 40, 30));

        aleDemanda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda2ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 40, 30));

        aleDemanda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda3ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 40, 30));

        aleDemanda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda4ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 40, 30));

        aleDemanda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda5ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 40, 30));

        aleDemanda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda6ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 40, 30));

        aleDemanda7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda7ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 40, 30));

        aleDemanda8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda8ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 40, 30));

        aleDemanda9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda9ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 40, 30));

        aleDemanda10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda10ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 40, 30));

        aleDemanda11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda11ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 40, 30));

        aleDemanda12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleDemanda12ActionPerformed(evt);
            }
        });
        getContentPane().add(aleDemanda12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 40, 30));

        jLabel7.setText("R");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demandaFr5TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demandaFr5TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demandaFr5TxtActionPerformed

    private void demandaFr3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demandaFr3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demandaFr3TxtActionPerformed

    private void demandaFa5TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demandaFa5TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demandaFa5TxtActionPerformed

    private void demandaFa3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demandaFa3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demandaFa3TxtActionPerformed

    private void retrasoFr5TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrasoFr5TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrasoFr5TxtActionPerformed

    private void retrasoFr3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrasoFr3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrasoFr3TxtActionPerformed

    private void retrasoFa5TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrasoFa5TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrasoFa5TxtActionPerformed

    private void retrasoFa3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrasoFa3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrasoFa3TxtActionPerformed

    private void puntoReordenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoReordenTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntoReordenTxtActionPerformed

    private void aleRetraso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso1ActionPerformed

    private void aleRetraso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso2ActionPerformed

    private void aleRetraso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso3ActionPerformed

    private void aleRetraso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso4ActionPerformed

    private void aleRetraso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso5ActionPerformed

    private void aleRetraso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso6ActionPerformed

    private void aleRetraso7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso7ActionPerformed

    private void aleRetraso8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso8ActionPerformed

    private void aleRetraso9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso9ActionPerformed

    private void aleRetraso10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso10ActionPerformed

    private void aleRetraso11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso11ActionPerformed

    private void aleRetraso12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleRetraso12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleRetraso12ActionPerformed

    private void aleDemanda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda1ActionPerformed

    private void aleDemanda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda2ActionPerformed

    private void aleDemanda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda3ActionPerformed

    private void aleDemanda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda4ActionPerformed

    private void aleDemanda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda5ActionPerformed

    private void aleDemanda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda6ActionPerformed

    private void aleDemanda7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda7ActionPerformed

    private void aleDemanda8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda8ActionPerformed

    private void aleDemanda9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda9ActionPerformed

    private void aleDemanda10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda10ActionPerformed

    private void aleDemanda11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda11ActionPerformed

    private void aleDemanda12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleDemanda12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aleDemanda12ActionPerformed

    float [][] datos =  new float[12][10];
    Object [][] datosTabla =  new Object[12][10];
     float [] demanda = new float[5];
      float [] retraso = new float[5];
    float [] dfrecuenciA = new float[5];
       float [] dfrecuenciR = new float[5];
       float [] rfrecuenciA = new float[5];
       float [] rfrecuenciR = new float[5];
       float [] aleDemanda = new float[12];
      float [] aleRetraso = new float[12];
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     
        //Conversion de textfields
       demanda[0] = (demanda1Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demanda1Txt.getText()));
       demanda[1] = (demanda2Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demanda2Txt.getText()));
       demanda[2] = (demanda3Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demanda3Txt.getText()));
       demanda[3] = (demanda4Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demanda4Txt.getText()));
       demanda[4] = (demanda5Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demanda5Txt.getText()));
       
       retraso[0] = (retraso1Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retraso1Txt.getText()));
       retraso[1] = (retraso2Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retraso2Txt.getText()));
       retraso[2] = (retraso3Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retraso3Txt.getText()));
       retraso[3] = (retraso4Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retraso4Txt.getText()));
       retraso[4] = (retraso5Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retraso5Txt.getText()));
       
        dfrecuenciR[0] =(demandaFr1Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demandaFr1Txt.getText()));
        dfrecuenciR[1] = (demandaFr2Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demandaFr2Txt.getText()));
        dfrecuenciR[2] = (demandaFr3Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demandaFr3Txt.getText()));
        dfrecuenciR[3] = (demandaFr4Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demandaFr4Txt.getText()));
        dfrecuenciR[4] = (demandaFr5Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demandaFr5Txt.getText()));
        
        rfrecuenciR[0] =(retrasoFr1Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retrasoFr1Txt.getText()));
        rfrecuenciR[1] =(retrasoFr2Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retrasoFr2Txt.getText()));
        rfrecuenciR[2] =(retrasoFr3Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retrasoFr3Txt.getText()));
        rfrecuenciR[3] =(retrasoFr4Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retrasoFr4Txt.getText()));
        rfrecuenciR[4] =(retrasoFr5Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retrasoFr5Txt.getText()));
               
       dfrecuenciA[0] =(demandaFr1Txt.getText().isEmpty()== true ? 0 : Float.valueOf( demandaFr1Txt.getText()));
       rfrecuenciA[0] =(retrasoFr1Txt.getText().isEmpty()== true ? 0 : Float.valueOf( retrasoFr1Txt.getText()));
        
       for(int i=1; i < 5 ; i++)
       {
            dfrecuenciA[i] = dfrecuenciA[i-1] + dfrecuenciR[i];
            rfrecuenciA[i] = rfrecuenciA[i-1] + rfrecuenciR[i];
            
            if(dfrecuenciA[i]>1 ||   rfrecuenciA[i]>1 )
            {
                JOptionPane.showMessageDialog(null, "La frecuencia exedio la unidad.", "Corrija los datos. " , JOptionPane.INFORMATION_MESSAGE);
               
            }
            
                   
       }
            
            
            
            float dAleatorio1 = (aleDemanda1.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda1.getText()));
            float dAleatorio2 = (aleDemanda2.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda2.getText()));
            float dAleatorio3 = (aleDemanda3.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda3.getText()));
            float dAleatorio4 = (aleDemanda4.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda4.getText()));
            float dAleatorio5 = (aleDemanda5.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda5.getText()));
            float dAleatorio6 = (aleDemanda6.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda6.getText()));
            float dAleatorio7 = (aleDemanda7.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda7.getText()));
            float dAleatorio8 = (aleDemanda8.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda8.getText()));
            float dAleatorio9 = (aleDemanda9.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda9.getText()));
            float dAleatorio10 = (aleDemanda10.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda10.getText()));
            float dAleatorio11 = (aleDemanda11.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda11.getText()));
            float dAleatorio12 = (aleDemanda12.getText().isEmpty()== true ? -1 : Float.valueOf( aleDemanda12.getText()));
            aleDemanda[0]=dAleatorio1;
            aleDemanda[1]=dAleatorio2;
            aleDemanda[2]=dAleatorio3;
            aleDemanda[3]=dAleatorio4;
             aleDemanda[4]=dAleatorio5;
              aleDemanda[5]=dAleatorio6;
               aleDemanda[6]=dAleatorio7;
                aleDemanda[7]=dAleatorio8;
                 aleDemanda[8]=dAleatorio9;
           aleDemanda[9]=dAleatorio10;
           aleDemanda[10]=dAleatorio11;
           aleDemanda[11]=dAleatorio12;
            
            float rAleatorio1 =  (aleRetraso1.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso1.getText()));
            float rAleatorio2 =  (aleRetraso2.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso2.getText()));
            float rAleatorio3 =  (aleRetraso3.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso3.getText()));
            float rAleatorio4 =  (aleRetraso4.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso4.getText()));
            float rAleatorio5 =  (aleRetraso5.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso5.getText()));
            float rAleatorio6 =  (aleRetraso6.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso6.getText()));
            float rAleatorio7 =  (aleRetraso7.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso7.getText()));
            float rAleatorio8 =  (aleRetraso8.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso8.getText()));
            float rAleatorio9 =  (aleRetraso9.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso9.getText()));
            float rAleatorio10 =  (aleRetraso10.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso10.getText()));
            float rAleatorio11 =  (aleRetraso11.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso11.getText()));
            float rAleatorio12 =  (aleRetraso12.getText().isEmpty()== true ? -1 : Float.valueOf( aleRetraso12.getText()));
            aleRetraso[0] = rAleatorio1;
            aleRetraso[1] = rAleatorio2;
            aleRetraso[2] = rAleatorio3;
            aleRetraso[3] = rAleatorio4;
            aleRetraso[4] = rAleatorio5;
            aleRetraso[5] = rAleatorio6;
            aleRetraso[6] = rAleatorio7;
            aleRetraso[7] = rAleatorio8;
            aleRetraso[8] = rAleatorio9;
            aleRetraso[9] = rAleatorio10;
            aleRetraso[10] = rAleatorio11;
            aleRetraso[11] = rAleatorio12;
            
    
        
        
        
        // TODO add your handling code here:
        float inventario = Float.valueOf(inventarioInicialTxt.getText());
         float cantidadPorPedido = Float.valueOf(cantidadPedidoTxt.getText());
         float puntoReorden = Float.valueOf(puntoReordenTxt.getText());
        float retrasoPedido = 0;
        int indexRetraso = 0;
        Boolean llegoPedido = false;
        Boolean enEsperaPedido = false;
        //enEsperaPedido = false;
        for(int i=0; i < 12 ; i++)
        {
            retrasoPedido--;
                 
                 if(retrasoPedido==0)
                 {
                     datos[i][1] = cantidadPorPedido; 
                     llegoPedido = true;
                     retrasoPedido = -1;
                 }else
                 {
                     datos[i][1] = 0;
                 }
            datos[i][0]= i+1;
            datos[i][3]= aleDemanda[i];
            datos[i][2] = inventario;
            if(llegoPedido==true)
            {
                inventario +=Float.valueOf( cantidadPedidoTxt.getText());
                
                llegoPedido = false;
                enEsperaPedido = false;
            }
            
            datos[i][2] = inventario;
            
            
              datos[i][4] = encontrarRangoD(aleDemanda[i]);
              datos[i][2] = inventario;
              
              //Inventario
                 datos[i][2] = inventario;
                 
                 if ((inventario -  datos[i][4])<= 0)
                 {
                     datos[i][5] = 0;
                     float temp = datos[i][4];
                     
                    datos[i][6]= Math.abs(inventario -  temp);
                     
                 }
                 else
                 { 
                     datos[i][5] = inventario - datos[i][4];
                 }
                 
                 
                 if(datos[i][5] <= puntoReorden && retrasoPedido <= 0 && enEsperaPedido == false)
                 {
                     datos[i][8] = aleRetraso[indexRetraso];
                     datos[i][9] = encontrarRangoR(aleRetraso[indexRetraso]);
                     retrasoPedido = datos[i][9];
                     indexRetraso++;
                     enEsperaPedido = true;
                     datos[i][7] = cantidadPorPedido; 
                     
                 }
                 else
                 {
                  datos[i][8] = 0;
                     datos[i][9] = 0;   
                     datos[i][7] =0;
                 }
                 
                 datos[i][3] = aleDemanda[i];
                 /*if( datos[i][5] <=  puntoReorden)
                 {
                      datos[i][7] = cantidadPorPedido; 
                 }
                 else
                 {
                     datos[i][7] =0;
                 }*/
                 
                 if(datos[i][5]<0)
                 {
                     datos[i][6] = ( datos[i][5] * (-1)) +  datos[i][2]; 
                 }
                 else
                 {
                     datos[i][6] = 0; 
                     
                 }
                 
                 
                 
                 
                 inventario = datos[i][5];
                 
        }
        
        
        for(int j =0;j<12;j++)
                 {
                     for(int k =0;k<10;k++)
                 {
                     if(datos[j][3] != -1)
                     {
                     datosTabla[j][k]= datos[j][k];
                     }
                     else
                     {
                         break;
                     }
                 }
                 }
        Tabla miTabla = new Tabla(datosTabla);
        miTabla.setVisible(true);
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void demanda1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demanda1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demanda1TxtActionPerformed

    private void retraso1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retraso1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retraso1TxtActionPerformed

    public Float encontrarRangoD(float value)
    {
        for(int i=0; i < 5 ; i++)
       {
           float comp= dfrecuenciA[i];
           if(value < comp)
           {
              return demanda[i];
           }
           
           
                   
       }
           return 0f;
           
    }
    
     public Float encontrarRangoR(float value)
    {
        for(int i=1; i < 5 ; i++)
       {
           float comp= rfrecuenciA[i];
           if(value < comp)
           {
              return demanda[i];
           }
           
           
                   
       }
           return 0f;
           
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingreso().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aleDemanda1;
    private javax.swing.JTextField aleDemanda10;
    private javax.swing.JTextField aleDemanda11;
    private javax.swing.JTextField aleDemanda12;
    private javax.swing.JTextField aleDemanda2;
    private javax.swing.JTextField aleDemanda3;
    private javax.swing.JTextField aleDemanda4;
    private javax.swing.JTextField aleDemanda5;
    private javax.swing.JTextField aleDemanda6;
    private javax.swing.JTextField aleDemanda7;
    private javax.swing.JTextField aleDemanda8;
    private javax.swing.JTextField aleDemanda9;
    private javax.swing.JTextField aleRetraso1;
    private javax.swing.JTextField aleRetraso10;
    private javax.swing.JTextField aleRetraso11;
    private javax.swing.JTextField aleRetraso12;
    private javax.swing.JTextField aleRetraso2;
    private javax.swing.JTextField aleRetraso3;
    private javax.swing.JTextField aleRetraso4;
    private javax.swing.JTextField aleRetraso5;
    private javax.swing.JTextField aleRetraso6;
    private javax.swing.JTextField aleRetraso7;
    private javax.swing.JTextField aleRetraso8;
    private javax.swing.JTextField aleRetraso9;
    private javax.swing.JTextField cantidadPedidoTxt;
    private javax.swing.JTextField demanda1Txt;
    private javax.swing.JTextField demanda2Txt;
    private javax.swing.JTextField demanda3Txt;
    private javax.swing.JTextField demanda4Txt;
    private javax.swing.JTextField demanda5Txt;
    private javax.swing.JTextField demandaFa1Txt;
    private javax.swing.JTextField demandaFa2Txt;
    private javax.swing.JTextField demandaFa3Txt;
    private javax.swing.JTextField demandaFa4Txt;
    private javax.swing.JTextField demandaFa5Txt;
    private javax.swing.JTextField demandaFr1Txt;
    private javax.swing.JTextField demandaFr2Txt;
    private javax.swing.JTextField demandaFr3Txt;
    private javax.swing.JTextField demandaFr4Txt;
    private javax.swing.JTextField demandaFr5Txt;
    private javax.swing.JTextField inventarioInicialTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField puntoReordenTxt;
    private javax.swing.JTextField retraso1Txt;
    private javax.swing.JTextField retraso2Txt;
    private javax.swing.JTextField retraso3Txt;
    private javax.swing.JTextField retraso4Txt;
    private javax.swing.JTextField retraso5Txt;
    private javax.swing.JTextField retrasoFa1Txt;
    private javax.swing.JTextField retrasoFa2Txt;
    private javax.swing.JTextField retrasoFa3Txt;
    private javax.swing.JTextField retrasoFa4Txt;
    private javax.swing.JTextField retrasoFa5Txt;
    private javax.swing.JTextField retrasoFr1Txt;
    private javax.swing.JTextField retrasoFr2Txt;
    private javax.swing.JTextField retrasoFr3Txt;
    private javax.swing.JTextField retrasoFr4Txt;
    private javax.swing.JTextField retrasoFr5Txt;
    // End of variables declaration//GEN-END:variables
}
